apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manul-server-storage
  namespace: default
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 30Gi
