// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.31.1
// source: cat_photos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CatPhotosServiceClient is the client API for CatPhotosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatPhotosServiceClient interface {
	ListCats(ctx context.Context, in *ListCatsRequest, opts ...grpc.CallOption) (*ListCatsResponse, error)
	ListPhotos(ctx context.Context, in *ListPhotosRequest, opts ...grpc.CallOption) (*ListPhotosResponse, error)
	GetPhoto(ctx context.Context, in *GetPhotoRequest, opts ...grpc.CallOption) (*GetPhotoResponse, error)
}

type catPhotosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatPhotosServiceClient(cc grpc.ClientConnInterface) CatPhotosServiceClient {
	return &catPhotosServiceClient{cc}
}

func (c *catPhotosServiceClient) ListCats(ctx context.Context, in *ListCatsRequest, opts ...grpc.CallOption) (*ListCatsResponse, error) {
	out := new(ListCatsResponse)
	err := c.cc.Invoke(ctx, "/catphotos.CatPhotosService/ListCats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catPhotosServiceClient) ListPhotos(ctx context.Context, in *ListPhotosRequest, opts ...grpc.CallOption) (*ListPhotosResponse, error) {
	out := new(ListPhotosResponse)
	err := c.cc.Invoke(ctx, "/catphotos.CatPhotosService/ListPhotos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catPhotosServiceClient) GetPhoto(ctx context.Context, in *GetPhotoRequest, opts ...grpc.CallOption) (*GetPhotoResponse, error) {
	out := new(GetPhotoResponse)
	err := c.cc.Invoke(ctx, "/catphotos.CatPhotosService/GetPhoto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatPhotosServiceServer is the server API for CatPhotosService service.
// All implementations must embed UnimplementedCatPhotosServiceServer
// for forward compatibility
type CatPhotosServiceServer interface {
	ListCats(context.Context, *ListCatsRequest) (*ListCatsResponse, error)
	ListPhotos(context.Context, *ListPhotosRequest) (*ListPhotosResponse, error)
	GetPhoto(context.Context, *GetPhotoRequest) (*GetPhotoResponse, error)
	mustEmbedUnimplementedCatPhotosServiceServer()
}

// UnimplementedCatPhotosServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCatPhotosServiceServer struct {
}

func (UnimplementedCatPhotosServiceServer) ListCats(context.Context, *ListCatsRequest) (*ListCatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCats not implemented")
}
func (UnimplementedCatPhotosServiceServer) ListPhotos(context.Context, *ListPhotosRequest) (*ListPhotosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPhotos not implemented")
}
func (UnimplementedCatPhotosServiceServer) GetPhoto(context.Context, *GetPhotoRequest) (*GetPhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPhoto not implemented")
}
func (UnimplementedCatPhotosServiceServer) mustEmbedUnimplementedCatPhotosServiceServer() {}

// UnsafeCatPhotosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatPhotosServiceServer will
// result in compilation errors.
type UnsafeCatPhotosServiceServer interface {
	mustEmbedUnimplementedCatPhotosServiceServer()
}

func RegisterCatPhotosServiceServer(s grpc.ServiceRegistrar, srv CatPhotosServiceServer) {
	s.RegisterService(&CatPhotosService_ServiceDesc, srv)
}

func _CatPhotosService_ListCats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatPhotosServiceServer).ListCats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catphotos.CatPhotosService/ListCats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatPhotosServiceServer).ListCats(ctx, req.(*ListCatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatPhotosService_ListPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatPhotosServiceServer).ListPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catphotos.CatPhotosService/ListPhotos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatPhotosServiceServer).ListPhotos(ctx, req.(*ListPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatPhotosService_GetPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatPhotosServiceServer).GetPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catphotos.CatPhotosService/GetPhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatPhotosServiceServer).GetPhoto(ctx, req.(*GetPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatPhotosService_ServiceDesc is the grpc.ServiceDesc for CatPhotosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatPhotosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catphotos.CatPhotosService",
	HandlerType: (*CatPhotosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCats",
			Handler:    _CatPhotosService_ListCats_Handler,
		},
		{
			MethodName: "ListPhotos",
			Handler:    _CatPhotosService_ListPhotos_Handler,
		},
		{
			MethodName: "GetPhoto",
			Handler:    _CatPhotosService_GetPhoto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cat_photos.proto",
}
