// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: cat_photos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalingAlgorithm int32

const (
	ScalingAlgorithm_NEAREST_NEIGHBOR ScalingAlgorithm = 0
	ScalingAlgorithm_BILINEAR         ScalingAlgorithm = 1
	ScalingAlgorithm_CATMULL_ROM      ScalingAlgorithm = 2
	ScalingAlgorithm_APPROX_BILINEAR  ScalingAlgorithm = 3
)

// Enum value maps for ScalingAlgorithm.
var (
	ScalingAlgorithm_name = map[int32]string{
		0: "NEAREST_NEIGHBOR",
		1: "BILINEAR",
		2: "CATMULL_ROM",
		3: "APPROX_BILINEAR",
	}
	ScalingAlgorithm_value = map[string]int32{
		"NEAREST_NEIGHBOR": 0,
		"BILINEAR":         1,
		"CATMULL_ROM":      2,
		"APPROX_BILINEAR":  3,
	}
)

func (x ScalingAlgorithm) Enum() *ScalingAlgorithm {
	p := new(ScalingAlgorithm)
	*p = x
	return p
}

func (x ScalingAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalingAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_cat_photos_proto_enumTypes[0].Descriptor()
}

func (ScalingAlgorithm) Type() protoreflect.EnumType {
	return &file_cat_photos_proto_enumTypes[0]
}

func (x ScalingAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalingAlgorithm.Descriptor instead.
func (ScalingAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{0}
}

type ListCatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatsRequest) Reset() {
	*x = ListCatsRequest{}
	mi := &file_cat_photos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatsRequest) ProtoMessage() {}

func (x *ListCatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatsRequest.ProtoReflect.Descriptor instead.
func (*ListCatsRequest) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{0}
}

type ListCatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatIds        []uint64               `protobuf:"varint,1,rep,packed,name=cat_ids,json=catIds,proto3" json:"cat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatsResponse) Reset() {
	*x = ListCatsResponse{}
	mi := &file_cat_photos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatsResponse) ProtoMessage() {}

func (x *ListCatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatsResponse.ProtoReflect.Descriptor instead.
func (*ListCatsResponse) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{1}
}

func (x *ListCatsResponse) GetCatIds() []uint64 {
	if x != nil {
		return x.CatIds
	}
	return nil
}

type ListPhotosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatId         uint64                 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhotosRequest) Reset() {
	*x = ListPhotosRequest{}
	mi := &file_cat_photos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhotosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosRequest) ProtoMessage() {}

func (x *ListPhotosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosRequest.ProtoReflect.Descriptor instead.
func (*ListPhotosRequest) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{2}
}

func (x *ListPhotosRequest) GetCatId() uint64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type ListPhotosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhotoIds      []uint64               `protobuf:"varint,1,rep,packed,name=photo_ids,json=photoIds,proto3" json:"photo_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhotosResponse) Reset() {
	*x = ListPhotosResponse{}
	mi := &file_cat_photos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhotosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosResponse) ProtoMessage() {}

func (x *ListPhotosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosResponse.ProtoReflect.Descriptor instead.
func (*ListPhotosResponse) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{3}
}

func (x *ListPhotosResponse) GetPhotoIds() []uint64 {
	if x != nil {
		return x.PhotoIds
	}
	return nil
}

type GetPhotoRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CatId            uint64                 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	PhotoId          uint64                 `protobuf:"varint,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	Width            uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	ScalingAlgorithm ScalingAlgorithm       `protobuf:"varint,4,opt,name=scaling_algorithm,json=scalingAlgorithm,proto3,enum=catphotos.ScalingAlgorithm" json:"scaling_algorithm,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPhotoRequest) Reset() {
	*x = GetPhotoRequest{}
	mi := &file_cat_photos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotoRequest) ProtoMessage() {}

func (x *GetPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotoRequest.ProtoReflect.Descriptor instead.
func (*GetPhotoRequest) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{4}
}

func (x *GetPhotoRequest) GetCatId() uint64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *GetPhotoRequest) GetPhotoId() uint64 {
	if x != nil {
		return x.PhotoId
	}
	return 0
}

func (x *GetPhotoRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetPhotoRequest) GetScalingAlgorithm() ScalingAlgorithm {
	if x != nil {
		return x.ScalingAlgorithm
	}
	return ScalingAlgorithm_NEAREST_NEIGHBOR
}

type GetPhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhotoData     []byte                 `protobuf:"bytes,1,opt,name=photo_data,json=photoData,proto3" json:"photo_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhotoResponse) Reset() {
	*x = GetPhotoResponse{}
	mi := &file_cat_photos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotoResponse) ProtoMessage() {}

func (x *GetPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotoResponse.ProtoReflect.Descriptor instead.
func (*GetPhotoResponse) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{5}
}

func (x *GetPhotoResponse) GetPhotoData() []byte {
	if x != nil {
		return x.PhotoData
	}
	return nil
}

type PhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatId         uint64                 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	PhotoId       uint64                 `protobuf:"varint,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoRequest) Reset() {
	*x = PhotoRequest{}
	mi := &file_cat_photos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoRequest) ProtoMessage() {}

func (x *PhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoRequest.ProtoReflect.Descriptor instead.
func (*PhotoRequest) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{6}
}

func (x *PhotoRequest) GetCatId() uint64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *PhotoRequest) GetPhotoId() uint64 {
	if x != nil {
		return x.PhotoId
	}
	return 0
}

type GetPhotosStreamRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PhotoRequests    []*PhotoRequest        `protobuf:"bytes,1,rep,name=photo_requests,json=photoRequests,proto3" json:"photo_requests,omitempty"`
	Width            uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	ScalingAlgorithm ScalingAlgorithm       `protobuf:"varint,3,opt,name=scaling_algorithm,json=scalingAlgorithm,proto3,enum=catphotos.ScalingAlgorithm" json:"scaling_algorithm,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPhotosStreamRequest) Reset() {
	*x = GetPhotosStreamRequest{}
	mi := &file_cat_photos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotosStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotosStreamRequest) ProtoMessage() {}

func (x *GetPhotosStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotosStreamRequest.ProtoReflect.Descriptor instead.
func (*GetPhotosStreamRequest) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{7}
}

func (x *GetPhotosStreamRequest) GetPhotoRequests() []*PhotoRequest {
	if x != nil {
		return x.PhotoRequests
	}
	return nil
}

func (x *GetPhotosStreamRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetPhotosStreamRequest) GetScalingAlgorithm() ScalingAlgorithm {
	if x != nil {
		return x.ScalingAlgorithm
	}
	return ScalingAlgorithm_NEAREST_NEIGHBOR
}

type GetPhotosStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatId         uint64                 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	PhotoId       uint64                 `protobuf:"varint,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	PhotoData     []byte                 `protobuf:"bytes,3,opt,name=photo_data,json=photoData,proto3" json:"photo_data,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhotosStreamResponse) Reset() {
	*x = GetPhotosStreamResponse{}
	mi := &file_cat_photos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotosStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotosStreamResponse) ProtoMessage() {}

func (x *GetPhotosStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotosStreamResponse.ProtoReflect.Descriptor instead.
func (*GetPhotosStreamResponse) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{8}
}

func (x *GetPhotosStreamResponse) GetCatId() uint64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *GetPhotosStreamResponse) GetPhotoId() uint64 {
	if x != nil {
		return x.PhotoId
	}
	return 0
}

func (x *GetPhotosStreamResponse) GetPhotoData() []byte {
	if x != nil {
		return x.PhotoData
	}
	return nil
}

func (x *GetPhotosStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPhotosStreamResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_cat_photos_proto protoreflect.FileDescriptor

const file_cat_photos_proto_rawDesc = "" +
	"\n" +
	"\x10cat_photos.proto\x12\tcatphotos\"\x11\n" +
	"\x0fListCatsRequest\"+\n" +
	"\x10ListCatsResponse\x12\x17\n" +
	"\acat_ids\x18\x01 \x03(\x04R\x06catIds\"*\n" +
	"\x11ListPhotosRequest\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x04R\x05catId\"1\n" +
	"\x12ListPhotosResponse\x12\x1b\n" +
	"\tphoto_ids\x18\x01 \x03(\x04R\bphotoIds\"\xa3\x01\n" +
	"\x0fGetPhotoRequest\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x04R\x05catId\x12\x19\n" +
	"\bphoto_id\x18\x02 \x01(\x04R\aphotoId\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12H\n" +
	"\x11scaling_algorithm\x18\x04 \x01(\x0e2\x1b.catphotos.ScalingAlgorithmR\x10scalingAlgorithm\"1\n" +
	"\x10GetPhotoResponse\x12\x1d\n" +
	"\n" +
	"photo_data\x18\x01 \x01(\fR\tphotoData\"@\n" +
	"\fPhotoRequest\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x04R\x05catId\x12\x19\n" +
	"\bphoto_id\x18\x02 \x01(\x04R\aphotoId\"\xb8\x01\n" +
	"\x16GetPhotosStreamRequest\x12>\n" +
	"\x0ephoto_requests\x18\x01 \x03(\v2\x17.catphotos.PhotoRequestR\rphotoRequests\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12H\n" +
	"\x11scaling_algorithm\x18\x03 \x01(\x0e2\x1b.catphotos.ScalingAlgorithmR\x10scalingAlgorithm\"\xa9\x01\n" +
	"\x17GetPhotosStreamResponse\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x04R\x05catId\x12\x19\n" +
	"\bphoto_id\x18\x02 \x01(\x04R\aphotoId\x12\x1d\n" +
	"\n" +
	"photo_data\x18\x03 \x01(\fR\tphotoData\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage*\\\n" +
	"\x10ScalingAlgorithm\x12\x14\n" +
	"\x10NEAREST_NEIGHBOR\x10\x00\x12\f\n" +
	"\bBILINEAR\x10\x01\x12\x0f\n" +
	"\vCATMULL_ROM\x10\x02\x12\x13\n" +
	"\x0fAPPROX_BILINEAR\x10\x032\xc3\x02\n" +
	"\x10CatPhotosService\x12C\n" +
	"\bListCats\x12\x1a.catphotos.ListCatsRequest\x1a\x1b.catphotos.ListCatsResponse\x12I\n" +
	"\n" +
	"ListPhotos\x12\x1c.catphotos.ListPhotosRequest\x1a\x1d.catphotos.ListPhotosResponse\x12C\n" +
	"\bGetPhoto\x12\x1a.catphotos.GetPhotoRequest\x1a\x1b.catphotos.GetPhotoResponse\x12Z\n" +
	"\x0fGetPhotosStream\x12!.catphotos.GetPhotosStreamRequest\x1a\".catphotos.GetPhotosStreamResponse0\x01B\x1eZ\x1cgithub.com/mhbvr/manul/protob\x06proto3"

var (
	file_cat_photos_proto_rawDescOnce sync.Once
	file_cat_photos_proto_rawDescData []byte
)

func file_cat_photos_proto_rawDescGZIP() []byte {
	file_cat_photos_proto_rawDescOnce.Do(func() {
		file_cat_photos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cat_photos_proto_rawDesc), len(file_cat_photos_proto_rawDesc)))
	})
	return file_cat_photos_proto_rawDescData
}

var file_cat_photos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cat_photos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cat_photos_proto_goTypes = []any{
	(ScalingAlgorithm)(0),           // 0: catphotos.ScalingAlgorithm
	(*ListCatsRequest)(nil),         // 1: catphotos.ListCatsRequest
	(*ListCatsResponse)(nil),        // 2: catphotos.ListCatsResponse
	(*ListPhotosRequest)(nil),       // 3: catphotos.ListPhotosRequest
	(*ListPhotosResponse)(nil),      // 4: catphotos.ListPhotosResponse
	(*GetPhotoRequest)(nil),         // 5: catphotos.GetPhotoRequest
	(*GetPhotoResponse)(nil),        // 6: catphotos.GetPhotoResponse
	(*PhotoRequest)(nil),            // 7: catphotos.PhotoRequest
	(*GetPhotosStreamRequest)(nil),  // 8: catphotos.GetPhotosStreamRequest
	(*GetPhotosStreamResponse)(nil), // 9: catphotos.GetPhotosStreamResponse
}
var file_cat_photos_proto_depIdxs = []int32{
	0, // 0: catphotos.GetPhotoRequest.scaling_algorithm:type_name -> catphotos.ScalingAlgorithm
	7, // 1: catphotos.GetPhotosStreamRequest.photo_requests:type_name -> catphotos.PhotoRequest
	0, // 2: catphotos.GetPhotosStreamRequest.scaling_algorithm:type_name -> catphotos.ScalingAlgorithm
	1, // 3: catphotos.CatPhotosService.ListCats:input_type -> catphotos.ListCatsRequest
	3, // 4: catphotos.CatPhotosService.ListPhotos:input_type -> catphotos.ListPhotosRequest
	5, // 5: catphotos.CatPhotosService.GetPhoto:input_type -> catphotos.GetPhotoRequest
	8, // 6: catphotos.CatPhotosService.GetPhotosStream:input_type -> catphotos.GetPhotosStreamRequest
	2, // 7: catphotos.CatPhotosService.ListCats:output_type -> catphotos.ListCatsResponse
	4, // 8: catphotos.CatPhotosService.ListPhotos:output_type -> catphotos.ListPhotosResponse
	6, // 9: catphotos.CatPhotosService.GetPhoto:output_type -> catphotos.GetPhotoResponse
	9, // 10: catphotos.CatPhotosService.GetPhotosStream:output_type -> catphotos.GetPhotosStreamResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cat_photos_proto_init() }
func file_cat_photos_proto_init() {
	if File_cat_photos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cat_photos_proto_rawDesc), len(file_cat_photos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cat_photos_proto_goTypes,
		DependencyIndexes: file_cat_photos_proto_depIdxs,
		EnumInfos:         file_cat_photos_proto_enumTypes,
		MessageInfos:      file_cat_photos_proto_msgTypes,
	}.Build()
	File_cat_photos_proto = out.File
	file_cat_photos_proto_goTypes = nil
	file_cat_photos_proto_depIdxs = nil
}
