// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.32.0
// source: cat_photos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalingAlgorithm int32

const (
	ScalingAlgorithm_NEAREST_NEIGHBOR ScalingAlgorithm = 0
	ScalingAlgorithm_BILINEAR         ScalingAlgorithm = 1
	ScalingAlgorithm_CATMULL_ROM      ScalingAlgorithm = 2
	ScalingAlgorithm_APPROX_BILINEAR  ScalingAlgorithm = 3
)

// Enum value maps for ScalingAlgorithm.
var (
	ScalingAlgorithm_name = map[int32]string{
		0: "NEAREST_NEIGHBOR",
		1: "BILINEAR",
		2: "CATMULL_ROM",
		3: "APPROX_BILINEAR",
	}
	ScalingAlgorithm_value = map[string]int32{
		"NEAREST_NEIGHBOR": 0,
		"BILINEAR":         1,
		"CATMULL_ROM":      2,
		"APPROX_BILINEAR":  3,
	}
)

func (x ScalingAlgorithm) Enum() *ScalingAlgorithm {
	p := new(ScalingAlgorithm)
	*p = x
	return p
}

func (x ScalingAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalingAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_cat_photos_proto_enumTypes[0].Descriptor()
}

func (ScalingAlgorithm) Type() protoreflect.EnumType {
	return &file_cat_photos_proto_enumTypes[0]
}

func (x ScalingAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalingAlgorithm.Descriptor instead.
func (ScalingAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{0}
}

type ListCatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCatsRequest) Reset() {
	*x = ListCatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_photos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatsRequest) ProtoMessage() {}

func (x *ListCatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatsRequest.ProtoReflect.Descriptor instead.
func (*ListCatsRequest) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{0}
}

type ListCatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatIds []uint64 `protobuf:"varint,1,rep,packed,name=cat_ids,json=catIds,proto3" json:"cat_ids,omitempty"`
}

func (x *ListCatsResponse) Reset() {
	*x = ListCatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_photos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatsResponse) ProtoMessage() {}

func (x *ListCatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatsResponse.ProtoReflect.Descriptor instead.
func (*ListCatsResponse) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{1}
}

func (x *ListCatsResponse) GetCatIds() []uint64 {
	if x != nil {
		return x.CatIds
	}
	return nil
}

type ListPhotosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId uint64 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
}

func (x *ListPhotosRequest) Reset() {
	*x = ListPhotosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_photos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPhotosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosRequest) ProtoMessage() {}

func (x *ListPhotosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosRequest.ProtoReflect.Descriptor instead.
func (*ListPhotosRequest) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{2}
}

func (x *ListPhotosRequest) GetCatId() uint64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type ListPhotosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhotoIds []uint64 `protobuf:"varint,1,rep,packed,name=photo_ids,json=photoIds,proto3" json:"photo_ids,omitempty"`
}

func (x *ListPhotosResponse) Reset() {
	*x = ListPhotosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_photos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPhotosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosResponse) ProtoMessage() {}

func (x *ListPhotosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosResponse.ProtoReflect.Descriptor instead.
func (*ListPhotosResponse) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{3}
}

func (x *ListPhotosResponse) GetPhotoIds() []uint64 {
	if x != nil {
		return x.PhotoIds
	}
	return nil
}

type GetPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId            uint64           `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	PhotoId          uint64           `protobuf:"varint,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	Width            uint32           `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	ScalingAlgorithm ScalingAlgorithm `protobuf:"varint,4,opt,name=scaling_algorithm,json=scalingAlgorithm,proto3,enum=catphotos.ScalingAlgorithm" json:"scaling_algorithm,omitempty"`
}

func (x *GetPhotoRequest) Reset() {
	*x = GetPhotoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_photos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotoRequest) ProtoMessage() {}

func (x *GetPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotoRequest.ProtoReflect.Descriptor instead.
func (*GetPhotoRequest) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{4}
}

func (x *GetPhotoRequest) GetCatId() uint64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *GetPhotoRequest) GetPhotoId() uint64 {
	if x != nil {
		return x.PhotoId
	}
	return 0
}

func (x *GetPhotoRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetPhotoRequest) GetScalingAlgorithm() ScalingAlgorithm {
	if x != nil {
		return x.ScalingAlgorithm
	}
	return ScalingAlgorithm_NEAREST_NEIGHBOR
}

type GetPhotoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhotoData []byte `protobuf:"bytes,1,opt,name=photo_data,json=photoData,proto3" json:"photo_data,omitempty"`
}

func (x *GetPhotoResponse) Reset() {
	*x = GetPhotoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_photos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotoResponse) ProtoMessage() {}

func (x *GetPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_photos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotoResponse.ProtoReflect.Descriptor instead.
func (*GetPhotoResponse) Descriptor() ([]byte, []int) {
	return file_cat_photos_proto_rawDescGZIP(), []int{5}
}

func (x *GetPhotoResponse) GetPhotoData() []byte {
	if x != nil {
		return x.PhotoData
	}
	return nil
}

var File_cat_photos_proto protoreflect.FileDescriptor

var file_cat_photos_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x61, 0x74, 0x5f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x63, 0x61, 0x74, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x11, 0x0a,
	0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x2b, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x63, 0x61, 0x74, 0x49, 0x64, 0x73, 0x22, 0x2a, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x73, 0x22, 0xa3, 0x01, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x48, 0x0a, 0x11, 0x73, 0x63, 0x61, 0x6c,
	0x69, 0x6e, 0x67, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x63, 0x61, 0x74, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x52, 0x10, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x22, 0x31, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x5c, 0x0a, 0x10, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67,
	0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x14, 0x0a, 0x10, 0x4e, 0x45, 0x41,
	0x52, 0x45, 0x53, 0x54, 0x5f, 0x4e, 0x45, 0x49, 0x47, 0x48, 0x42, 0x4f, 0x52, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x42, 0x49, 0x4c, 0x49, 0x4e, 0x45, 0x41, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a,
	0x0b, 0x43, 0x41, 0x54, 0x4d, 0x55, 0x4c, 0x4c, 0x5f, 0x52, 0x4f, 0x4d, 0x10, 0x02, 0x12, 0x13,
	0x0a, 0x0f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x58, 0x5f, 0x42, 0x49, 0x4c, 0x49, 0x4e, 0x45, 0x41,
	0x52, 0x10, 0x03, 0x32, 0xe7, 0x01, 0x0a, 0x10, 0x43, 0x61, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x61, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x63, 0x61, 0x74, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x74, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x1c, 0x2e, 0x63, 0x61,
	0x74, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x61, 0x74, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x2e, 0x63, 0x61, 0x74, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x74, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a,
	0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x68, 0x62, 0x76,
	0x72, 0x2f, 0x6d, 0x61, 0x6e, 0x75, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cat_photos_proto_rawDescOnce sync.Once
	file_cat_photos_proto_rawDescData = file_cat_photos_proto_rawDesc
)

func file_cat_photos_proto_rawDescGZIP() []byte {
	file_cat_photos_proto_rawDescOnce.Do(func() {
		file_cat_photos_proto_rawDescData = protoimpl.X.CompressGZIP(file_cat_photos_proto_rawDescData)
	})
	return file_cat_photos_proto_rawDescData
}

var file_cat_photos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cat_photos_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cat_photos_proto_goTypes = []interface{}{
	(ScalingAlgorithm)(0),      // 0: catphotos.ScalingAlgorithm
	(*ListCatsRequest)(nil),    // 1: catphotos.ListCatsRequest
	(*ListCatsResponse)(nil),   // 2: catphotos.ListCatsResponse
	(*ListPhotosRequest)(nil),  // 3: catphotos.ListPhotosRequest
	(*ListPhotosResponse)(nil), // 4: catphotos.ListPhotosResponse
	(*GetPhotoRequest)(nil),    // 5: catphotos.GetPhotoRequest
	(*GetPhotoResponse)(nil),   // 6: catphotos.GetPhotoResponse
}
var file_cat_photos_proto_depIdxs = []int32{
	0, // 0: catphotos.GetPhotoRequest.scaling_algorithm:type_name -> catphotos.ScalingAlgorithm
	1, // 1: catphotos.CatPhotosService.ListCats:input_type -> catphotos.ListCatsRequest
	3, // 2: catphotos.CatPhotosService.ListPhotos:input_type -> catphotos.ListPhotosRequest
	5, // 3: catphotos.CatPhotosService.GetPhoto:input_type -> catphotos.GetPhotoRequest
	2, // 4: catphotos.CatPhotosService.ListCats:output_type -> catphotos.ListCatsResponse
	4, // 5: catphotos.CatPhotosService.ListPhotos:output_type -> catphotos.ListPhotosResponse
	6, // 6: catphotos.CatPhotosService.GetPhoto:output_type -> catphotos.GetPhotoResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cat_photos_proto_init() }
func file_cat_photos_proto_init() {
	if File_cat_photos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cat_photos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_photos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_photos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPhotosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_photos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPhotosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_photos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPhotoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_photos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPhotoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cat_photos_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cat_photos_proto_goTypes,
		DependencyIndexes: file_cat_photos_proto_depIdxs,
		EnumInfos:         file_cat_photos_proto_enumTypes,
		MessageInfos:      file_cat_photos_proto_msgTypes,
	}.Build()
	File_cat_photos_proto = out.File
	file_cat_photos_proto_rawDesc = nil
	file_cat_photos_proto_goTypes = nil
	file_cat_photos_proto_depIdxs = nil
}
